"""Universal broker integration framework (Phase 10)."""

from alpha_algo_broker_integration.base import BaseBrokerAdapter
from alpha_algo_broker_integration.connection import (
    ConnectionStateMachine,
    ReconnectPolicy,
    is_recoverable,
)
from alpha_algo_broker_integration.contracts import (
    BrokerAdapter,
    BrokerCapabilities,
    BrokerConnectionConfig,
    BrokerCredentialsRef,
    BrokerFundsSnapshot,
    BrokerHoldingSnapshot,
    BrokerName,
    BrokerOrderRequest,
    BrokerOrderResponse,
    BrokerOrderStatus,
    BrokerPositionSnapshot,
    BrokerSessionState,
    ConnectionState,
    OrderSide,
    OrderValidity,
    RetryPolicy,
    TradingMode,
    UniversalOrderType,
    UniversalProductType,
)
from alpha_algo_broker_integration.errors import (
    BrokerError,
    BrokerErrorClass,
    is_safe_to_retry,
    unknown_broker_error,
)
from alpha_algo_broker_integration.events import (
    BrokerEventType,
    DuplicateEventError,
    EventDeduplicator,
    NormalizedBrokerEvent,
    compute_event_identity,
)
from alpha_algo_broker_integration.mapping import (
    BrokerInstrument,
    InstrumentMapping,
    InstrumentSecurityType,
    require_supported,
    validate_quantity,
)
from alpha_algo_broker_integration.ratelimit import (
    RateLimiter,
    RateLimitPolicy,
    RateLimitScope,
    TokenBucket,
)
from alpha_algo_broker_integration.transport import (
    BrokerHttpTransport,
    FakeTransport,
    HttpxTransport,
    TransportResponse,
)

__all__ = [
    "BaseBrokerAdapter",
    "ConnectionStateMachine",
    "ReconnectPolicy",
    "is_recoverable",
    "BrokerAdapter",
    "BrokerCapabilities",
    "BrokerConnectionConfig",
    "BrokerCredentialsRef",
    "BrokerFundsSnapshot",
    "BrokerHoldingSnapshot",
    "BrokerName",
    "BrokerOrderRequest",
    "BrokerOrderResponse",
    "BrokerOrderStatus",
    "BrokerPositionSnapshot",
    "BrokerSessionState",
    "ConnectionState",
    "OrderSide",
    "OrderValidity",
    "RetryPolicy",
    "TradingMode",
    "UniversalOrderType",
    "UniversalProductType",
    "BrokerError",
    "BrokerErrorClass",
    "is_safe_to_retry",
    "unknown_broker_error",
    "BrokerEventType",
    "DuplicateEventError",
    "EventDeduplicator",
    "NormalizedBrokerEvent",
    "compute_event_identity",
    "BrokerInstrument",
    "InstrumentMapping",
    "InstrumentSecurityType",
    "require_supported",
    "validate_quantity",
    "RateLimiter",
    "RateLimitPolicy",
    "RateLimitScope",
    "TokenBucket",
    "BrokerHttpTransport",
    "FakeTransport",
    "HttpxTransport",
    "TransportResponse",
]
